# Site
name: 'BÒ NÉ 3 NGON'
description: 'Nhượng quyền bò né 3 ngon, hợp tác mở quán bò né 3 ngon, hổ trợ đứng bếp, Mở quán ở các tỉnh thành phố, Cung cấp nguyên liệu làm bò né'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: '3ngon'
email: 'bonengonsg@gmail.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           3ngon
      site:           https://bone3ngon.com.vn
      avatar:         /assets/images/avatar1.jpg
      bio:            "Chào bạn.mình có thể tư vấn về nhượng quyền bò né cho bạn được không ?"
      email:          bonengonsg@gmail.com
      twitter:        https://twitter.com/3ngon

    jane:
      name:           bone3ngon
      site:           https://bone3ngon.com.vn
      avatar:         /assets/images/avatar2.jpg
      bio:            "Chào bạn.mình có thể tư vấn về nhượng quyền bò né cho bạn được không ?"
      email:          bonengonsg@gmail.com
      twitter:        https://twitter.com/3ngon
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
